//Author: Jaydeep Rotithor
//Date: 10/26/2015
//Filename: rps.js
function play_rps(button){
//Document.write("hello");
if(button == ("rock")){//processes the user input
  document.getElementById("result").innerHTML = "You have chosen rock! <br/><img src = 'rock.jpg' alt = 'rock' class = 'img'>";
    var x =  generate_computer_object();//generates a random computer object
  document.getElementById("computer_object").innerHTML = "computer chose " + x;
//displays the appropriate message by comparing what the user chose to what was generated by the computer.
  if(x == "scissors"){
	  document.getElementById("end_result").innerHTML = "<br/><img src = 'scissors.jpg' alt = 'scissors' class = 'img'>"+"<br/>You win!";
	  document.getElementById("score").innerHTML ++;
  }
  else if(x == "paper"){
	  document.getElementById("end_result").innerHTML = "<img src = 'paper.jpg' alt = 'paper' class = 'img'>" + "<br/>You lose.";
	   document.getElementById("score2").innerHTML ++;
  
  }
  else if(x == "rock"){
	  document.getElementById("end_result").innerHTML = "<img src = 'rock.jpg' alt = 'rock' class = 'img'>" +"<br/>Tie game.";
	   document.getElementById("score3").innerHTML ++;
  }
} 
 else if(button == "paper"){//processes the user input
   document.getElementById("result").innerHTML = "You have chosen paper! <br/><img src = 'paper.jpg' alt = 'paper' class = 'img'>";
   var y = generate_computer_object();//generates a random computer object
 document.getElementById("computer_object").innerHTML = "computer chose " + y;
 //displays the appropriate message by comparing what the user chose to what was generated by the computer.
   if(y == "scissors"){
	  document.getElementById("end_result").innerHTML = "<br/><img src = 'scissors.jpg' alt = 'scissors' class = 'img'>"+"<br/>You lose.";
	   document.getElementById("score2").innerHTML ++;
   }
  else if(y == "paper"){
	  document.getElementById("end_result").innerHTML = "<img src = 'paper.jpg' alt = 'paper' class = 'img'>" + "<br/>Tie game.";
	   document.getElementById("score3").innerHTML ++;
  } 
 else if(y == "rock"){
	  document.getElementById("end_result").innerHTML = "<img src = 'rock.jpg' alt = 'rock' class = 'img'>" +"<br/>You win!";
	  document.getElementById("score").innerHTML ++;
 }
 }
   else if(button == "scissors"){//processes the user input
    document.getElementById("result").innerHTML = ("you have chosen scissors!<br/><img src = 'scissors.jpg' alt = 'scissors' class = 'img'>");
	var z =  generate_computer_object();//generates a random computer object
 document.getElementById("computer_object").innerHTML = "computer chose " + z;
 //displays the appropriate message by comparing what the user chose to what was generated by the computer.
   if(z == "scissors"){
	  document.getElementById("end_result").innerHTML = "<br/><img src = 'scissors.jpg' alt = 'scissors' class = 'img'>"+"<br/>Tie game.";
	   document.getElementById("score3").innerHTML ++;
   }
  else if(z == "paper"){
	  document.getElementById("end_result").innerHTML = "<img src = 'paper.jpg' alt = 'paper' class = 'img'>" + "<br/>You win!";
	  document.getElementById("score").innerHTML ++;
  } 
 else if(z == "rock"){
	  document.getElementById("end_result").innerHTML = "<img src = 'rock.jpg' alt = 'rock' class = 'img'>" +"<br/>You lose.";
	   document.getElementById("score2").innerHTML ++;
 }
   }
}
//randomly generates an object for the computer to use vs the user.
function generate_computer_object(){
	
	var x = Math.floor((Math.random() * 3) + 1);
	if(x == 1)
		return "rock";
	else if (x == 2)
		return "paper";
	else if ( x == 3);
		return "scissors";
	
	
}


//sets up an array of images to be used in the slideshow.

var slides = new Array(5);
slides[0] = "<img src = 'memorial_union.jpg' alt = 'mu' class = 'imgs'>"
slides[1] = "<img src = 'reser.jpg' alt = 'reser' class = 'imgs'>"
slides[2] = "<img src = 'gill.jpg' alt = 'basketball' class = 'imgs'>"
slides[3] = "<img src = 'weatherford.jpg' alt = 'weatherford' class = 'imgs'>"
slides[4] = "<img src = 'kelley.jpg' alt = 'kelley' class = 'imgs'>"
var i = 0;
//changes the slides of the array by increasing the index by 1. accounts for overflow by setting i 
//to 0 if it is greater than 4.
function change_slides(){
	

if(i < 4){
	i++;
document.getElementById("img1").innerHTML = slides[i];
}
else
{
	i = 0;
document.getElementById("img1").innerHTML = slides[i];

}

}
	




