function play_rps(button){
	var xmlhttp = new XMLHttpRequest();
		if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
		
		
	var wins = 0;

	
//Document.write("hello");
if(button == ("rock")){//processes the user input
  document.getElementById("result").innerHTML = "You have chosen rock! <br/><img src = 'A3_images/rock.jpg' alt = 'rock' class = 'img'>";
    var x =  generate_computer_object();//generates a random computer object
  document.getElementById("computer_object").innerHTML = "computer chose " + x;
//displays the appropriate message by comparing what the user chose to what was generated by the computer.
  if(x == "scissors"){
	  document.getElementById("end_result").innerHTML = "<br/><img src = 'A3_images/scissors.jpg' alt = 'scissors' class = 'img'>"+"<br/>You win!";
	  document.getElementById("score").innerHTML ++;
	  wins++;
  }
  else if(x == "paper"){
	  document.getElementById("end_result").innerHTML = "<img src = 'A3_images/paper.jpg' alt = 'paper' class = 'img'>" + "<br/>You lose.";
	   document.getElementById("score2").innerHTML ++;
  
  }
  else if(x == "rock"){
	  document.getElementById("end_result").innerHTML = "<img src = 'A3_images/rock.jpg' alt = 'rock' class = 'img'>" +"<br/>Tie game.";
	   document.getElementById("score3").innerHTML ++;
  }
} 
 else if(button == "paper"){//processes the user input
   document.getElementById("result").innerHTML = "You have chosen paper! <br/><img src = 'A3_images/paper.jpg' alt = 'paper' class = 'img'>";
   var y = generate_computer_object();//generates a random computer object
 document.getElementById("computer_object").innerHTML = "computer chose " + y;
 //displays the appropriate message by comparing what the user chose to what was generated by the computer.
   if(y == "scissors"){
	  document.getElementById("end_result").innerHTML = "<br/><img src = 'A3_images/scissors.jpg' alt = 'scissors' class = 'img'>"+"<br/>You lose.";
	   document.getElementById("score2").innerHTML ++;
   }
  else if(y == "paper"){
	  document.getElementById("end_result").innerHTML = "<img src = 'A3_images/paper.jpg' alt = 'paper' class = 'img'>" + "<br/>Tie game.";
	   document.getElementById("score3").innerHTML ++;
  } 
 else if(y == "rock"){
	  document.getElementById("end_result").innerHTML = "<img src = 'A3_images/rock.jpg' alt = 'rock' class = 'img'>" +"<br/>You win!";
	  document.getElementById("score").innerHTML ++;
	  wins++;
 }
 }
   else if(button == "scissors"){//processes the user input
    document.getElementById("result").innerHTML = ("you have chosen scissors!<br/><img src = 'A3_images/scissors.jpg' alt = 'scissors' class = 'img'>");
	var z =  generate_computer_object();//generates a random computer object
 document.getElementById("computer_object").innerHTML = "computer chose " + z;
 //displays the appropriate message by comparing what the user chose to what was generated by the computer.
   if(z == "scissors"){
	  document.getElementById("end_result").innerHTML = "<br/><img src = 'A3_images/scissors.jpg' alt = 'scissors' class = 'img'>"+"<br/>Tie game.";
	   document.getElementById("score3").innerHTML ++;
   }
  else if(z == "paper"){
	  document.getElementById("end_result").innerHTML = "<img src = 'A3_images/paper.jpg' alt = 'paper' class = 'img'>" + "<br/>You win!";
	  document.getElementById("score").innerHTML ++;
	  wins++;
  } 
 else if(z == "rock"){
	  document.getElementById("end_result").innerHTML = "<img src = 'A3_images/rock.jpg' alt = 'rock' class = 'img'>" +"<br/>You lose.";
	   document.getElementById("score2").innerHTML ++;
 }
   }
		}
   xmlhttp.open("GET", "rps_a5.php?q="+button,true);
	xmlhttp.send();
}
function get_result(button1){
		play_rps(button1);
//	
}
//randomly generates an object for the computer to use vs the user.
function generate_computer_object(){
	
	var x = Math.floor((Math.random() * 3) + 1);
	if(x == 1)
		return "rock";
	else if (x == 2)
		return "paper";
	else if ( x == 3);
		return "scissors";
	
	
}
function process_input(){


	if(document.getElementById("b1").checked == true)
		play_rps("rock");

	else if(document.getElementById("b2").checked == true)
		play_rps("paper");
	else if(document.getElementById("b3").checked == true)
		play_rps("scissors");
	
	
}

function print_wins(){
	document.getElementById("wins").innerHTML = wins;
}